services:
  backend:
    build: ./backend
    container_name: docatende_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - redis
      - rabbitmq

  frontend:
    build: ./frontend
    container_name: docatende_frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3005:3000"
    depends_on:
      - backend

  postgres:
    image: pgvector/pgvector:pg16
    container_name: docatende_postgres
    restart: always
    environment:
      POSTGRES_DB: docatende
      POSTGRES_USER: docatende
      POSTGRES_PASSWORD: docatende_password_123
    volumes:
      - docatende_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: docatende_redis
    restart: always

  rabbitmq:
   image: rabbitmq:3-management
   container_name: docatende_rabbitmq
   restart: always
   ports:
    - "15672:15672"

  worker:
    build: ./backend
    container_name: docatende_worker
    restart: always
    command: celery -A app.workers.celery_app:celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    volumes:
      - ./storage:/app/storage
    depends_on:
      - backend
      - rabbitmq
      - redis
      - postgres

volumes:
  docatende_postgres_data: